### Delete account
DELETE http://localhost:3001/account/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQ2ODYxMDAsImV4cCI6MTcxNDY4OTcwMH0.MEEstlYX8TSXTcDFYoUMUGP7OLso4bINLZPujlZFa9g

### Update account´s user
PATCH http://localhost:3001/account/1
Content-Type:  application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQxNDcwNjcsImV4cCI6MTcxNDE1MDY2N30.uY09SqDMgdlkwobPDAzJPJtenXQ4ursEUNJfKi-L35s

{
    "isAdmin": true
}

### Get account's profiles
GET http://localhost:3001/account/2/profiles
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTQxNDgxNzAsImV4cCI6MTcxNDE1MTc3MH0.kRDP6XxZ3R1ATpPLQAfcaoVhQNZdM7T01kkhBtINVgc

### Add profile to account
POST http://localhost:3001/account/1/profiles
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQ2ODYwNTQsImV4cCI6MTcxNDY4OTY1NH0.-u5t5XdRQm0SIxLpFrDMOik5GVxUywUIMtnwte1vkiw

{
    "username": "cousin"
}

### Delete profile from account
DELETE http://localhost:3001/account/2/profiles/10
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

### Update profile from account
PATCH http://localhost:3001/account/2/profiles/9
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

{
    "username":"friend"
}

### Get movies from profile´s wishlist
GET http://localhost:3001/account/3/profiles/16/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

### Add movie to profile´s wishlist
POST http://localhost:3001/account/1/profiles/1/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQ2OTcwNjUsImV4cCI6MTcxNDcwMDY2NX0.hcqFkxzLF5PPkbiczRX3kE-p4jpeVZBTkbrWSUiIh30

{
    "movieId":1
}

### Remove movie from profile´s wishlist
Delete http://localhost:3001/account/1/profiles/1/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

{
    "movieId":2
}

### Add movie to profile´s history
POST http://localhost:3001/account/1/profiles/1/history
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQ2OTcwNjUsImV4cCI6MTcxNDcwMDY2NX0.hcqFkxzLF5PPkbiczRX3kE-p4jpeVZBTkbrWSUiIh30

{
    "movieId":1
}

### Get movies from profile´s history
GET http://localhost:3001/account/2/profiles/2/history
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQ2ODY3MDUsImV4cCI6MTcxNDY5MDMwNX0.Tn7DPxMLPdShVHibqy6j6EzH8DEfQpwTDqmBCzpC5oc