### Delete account
DELETE http://localhost:3001/account/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5Mzc3MzcsImV4cCI6MTcxMzk0MTMzN30.4V21nGh1EcPojKXf0_wJMf30e_A-_gud-cDpZrRnItM

### Get account's profiles
GET http://localhost:3001/account/3/profiles
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

### Add profile to account
POST http://localhost:3001/account/3/profiles
Content-Type: application/json; charset=utf-8

{
    "username": "aunt"
}

### Delete profile from account
DELETE http://localhost:3001/account/2/profiles/10
Content-Type: application/json; charset=utf-8

### Update profile from account
PATCH http://localhost:3001/account/2/profiles/9
Content-Type: application/json; charset=utf-8

{
    "username":"friend"
}

### Get movies from profile´s wishlist
GET http://localhost:3001/account/3/profiles/16/wishlist
Content-Type: application/json; charset=utf-8

### Add movie to profile´s wishlist
POST http://localhost:3001/account/3/profiles/16/wishlist
Content-Type: application/json; charset=utf-8

{
    "movieId":2
}

### Remove movie from profile´s wishlist
Delete http://localhost:3001/account/1/profiles/1/wishlist
Content-Type: application/json; charset=utf-8

{
    "movieId":2
}