### Delete account
DELETE http://localhost:3001/account/3
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDEwNTMxMSwiZXhwIjoxNzE0MTA4OTExfQ.8G-2wkNMxdhoqz32g8mvAg1w_V0f_tgoOUadR4N0Lw4

### Update account´s user
PATCH http://localhost:3001/account/1
Content-Type:  application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTQwMjE0NDUsImV4cCI6MTcxNDAyNTA0NX0.SyRv7NeY1Qe3msCrY4VoHrM7jQCsQW_UKlzArbILrDw

{
    "password": "test",
}

### Get account's profiles
GET http://localhost:3001/account/7/profiles
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDEwNTMxMSwiZXhwIjoxNzE0MTA4OTExfQ.8G-2wkNMxdhoqz32g8mvAg1w_V0f_tgoOUadR4N0Lw4

### Add profile to account
POST http://localhost:3001/account/7/profiles
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDEwNTMxMSwiZXhwIjoxNzE0MTA4OTExfQ.8G-2wkNMxdhoqz32g8mvAg1w_V0f_tgoOUadR4N0Lw4

{
    "username": "aunt"
}

### Delete profile from account
DELETE http://localhost:3001/account/2/profiles/10
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

### Update profile from account
PATCH http://localhost:3001/account/2/profiles/9
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

{
    "username":"friend"
}

### Get movies from profile´s wishlist
GET http://localhost:3001/account/3/profiles/16/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

### Add movie to profile´s wishlist
POST http://localhost:3001/account/3/profiles/16/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

{
    "movieId":2
}

### Remove movie from profile´s wishlist
Delete http://localhost:3001/account/1/profiles/1/wishlist
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE3MTM5OTY0MTAsImV4cCI6MTcxNDAwMDAxMH0.MKb-Z8tiRM_T8_QxI8D64OfX527ANJzaJZmXYBAog_g

{
    "movieId":2
}