### Create account
POST http://localhost:3001/auth/sign-up
Content-Type: application/json; charset=utf-8

{
    "email": "test1@test.com",  
    "password": "test" ,   
    "firstName": "Omar"
}

### Generate account's token
POST http://localhost:3001/auth/sign-in
Content-Type: application/json; charset=utf-8

{
    "email": "test1@test.com",
    "password": "test" 
}