### Create user
POST http://localhost:3001/auth/sign-up
Content-Type: application/json; charset=utf-8

{
    "email": "test3@test.com",
    "password": "test" ,   
    "firstName": "Alejandro"
}

### Create user
POST http://localhost:3001/auth/sign-in
Content-Type: application/json; charset=utf-8

{
    "email": "test2@test.com",
    "password": "test" 
}