### Create movie
POST http://localhost:3001/movies
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxMTU4MTUzNSwiZXhwIjoxNzExNTg1MTM1fQ.GzR6s5mqRwSzU5giM-4Rh2ZefI8-cavM2BJJ6ESZATE

{
    "title": "Avengers Endgame",
    "year": 2021
}

### Update movie
PUT http://localhost:3001/movies/8
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxMTU4NTUyOCwiZXhwIjoxNzExNTg5MTI4fQ.W517pfjvT0fMElIzGncPTgoS4_kFZeBOPiZ53vjDrN0

{
    "year": 2022,
    "categories": ["Action","Superheroes"],
    "directors": ["Anthony Russo","Joe Russo"]
}


### Obtain movie
GET http://localhost:3001/movies
Content-Type: application/json; charset=utf-8

### Obtain movie by id

GET http://localhost:3001/movies/8

### Delete movie by id
Delete http://localhost:3001/movies/6