### Create movie
POST http://localhost:3001/movies
Content-Type: application/json; charset=utf-8

{
    "title": "Avengers",
    "year": 2008
}

### Obtain movie
GET http://localhost:3001/movies
Content-Type: application/json; charset=utf-8
