### Obtain users
GET http://localhost:3001/users
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDEwNTMxMSwiZXhwIjoxNzE0MTA4OTExfQ.8G-2wkNMxdhoqz32g8mvAg1w_V0f_tgoOUadR4N0Lw4


### Obtain user
GET http://localhost:3001/users/2
Content-Type: application/json; charset=utf-8

### Update user
PATCH http://localhost:3001/users/1
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDE0NzI0MiwiZXhwIjoxNzE0MTUwODQyfQ.G3lob46jIsNUUNgIZ8P8p-G0pAPmzxfzqJk6PSO92rg

{
    "isAdmin": false
}

### Create user
POST http://localhost:3001/users
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0ZXN0MUB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDE0NzI0MiwiZXhwIjoxNzE0MTUwODQyfQ.G3lob46jIsNUUNgIZ8P8p-G0pAPmzxfzqJk6PSO92rg

{
    "email": "admin@admin.com",  
    "password": "admin" ,   
    "firstName": "admin",
    "isAdmin": true
}

### Delete user
DELETE http://localhost:3001/users/6
Content-Type: application/json; charset=utf-8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ0ZXN0MkB0ZXN0LmNvbSIsImlzQWRtaW4iOnRydWUsImlhdCI6MTcxNDEwNTMxMSwiZXhwIjoxNzE0MTA4OTExfQ.8G-2wkNMxdhoqz32g8mvAg1w_V0f_tgoOUadR4N0Lw4
